#!/bin/bash

localdate="";
querytime="";

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
		-l|--local)
			localdate="$2"
			shift
			shift
			;;
		-q|--query)
			querytime="$2"
			shift
			shift
			;;
		*)  
			POSITIONAL+=("$1")
			shift
			;;
	esac
done

if [ -z "$localdate" ]; then
	localtime=$(date "+%Y-%m-%d %H:%M")
	localtz=$(date "+%z")
	localcity=$(cat /etc/timezone)
else
	echo ">1"
	#if [ ! -z $(echo "$localdate" | grep ",") ] ; then
	if [ $(echo "$localdate" | awk '{if ($localdate ~ /,/) {print "1";next} {print "0"}}') == 1 ]; then
		echo ">2"
		localtime=$(echo $localdate | cut -d "," -f 2)
		localcity=$(echo $localdate | cut -d "," -f 1)
	else
		if [ $(echo "$localdate" | awk '{if ($localdate ~ /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/) {print "1";next} { print "0"} }') == 1 ]; then
			localcity=$(cat /etc/timezone)
			localtime=$localdate
			localtz=$(TZ="$localcity" date "+%z")
		else
			localcity=$localdate
			localtime=$(date "+%Y-%m-%d %H:%M")
			localtz=$(date "+%z")
		fi
	fi
fi

tmp=$localcity

#Check if localcity is valid TZ or shuld find one valid
if [ ! -f "/usr/share/zoneinfo/$localcity" ]; then
		localcity=$(find "/usr/share/zoneinfo" -iname "*$localcity*" | grep -v "posix" | grep -v "right" | sed 's/\/usr\/share\/zoneinfo\///g')
fi

localtz=$(TZ="$localcity" date "+%z")

querytime=${querytime//,/$'\n'} 

if [ ! -f "/usr/share/zoneinfo/$localcity" ]; then
	echo "$tmp is a invalid TZ"
	exit;
fi

tmp=$(date --date "$localtime" +%s)
localtime=$(date --date "@$tmp" "+%Y-%m-%d %H:%M")

echo " "
echo " "
for str in $querytime 
do
	tmp=$str
	if [ ! -f "/usr/share/zoneinfo/$str" ]; then
		if ! echo "$str" | grep "/"; then
			str=$(find "/usr/share/zoneinfo" -iname "*$str*" | grep -v "posix" | grep -v "right" | sed 's/\/usr\/share\/zoneinfo\///g')
		fi
	fi

	if [ -f "/usr/share/zoneinfo/$str" ]; then
		TZ="$str" date "+%Y-%m-%d %H:%M" -d "$localtime $localtz " | tr -d '\n'
   		echo -e "$TZ $str"
	else
		echo "$tmp is a invalid TZ"
	fi
done
echo " "
echo " "
